import 'Screens/Shopping/provider/product.dart';

List<Product> medicines = [
  Product(
    id: "1",
    title: "Paracetamol Tablets",
    price: 50,
    category: "Medicine",
    description: "Effective for reducing pain and fever. Suitable for various conditions.",
  ),
  Product(
    id: "2",
    title: "Ibuprofen Capsules",
    price: 75,
    category: "Medicine",
    description: "Anti-inflammatory and pain-relieving capsules. Provides relief from various types of pain.",
  ),
  Product(
    id: "3",
    title: "Vitamin C Tablets",
    price: 100,
    category: "Medicine",
    description: "Boosts the immune system and helps maintain overall health. Essential for collagen production.",
  ),
  Product(
    id: "4",
    title: "Cetirizine Syrup",
    price: 80,
    category: "Medicine",
    description: "Antihistamine syrup for allergy relief. Provides relief from symptoms like sneezing and itching.",
  ),
  Product(
    id: "5",
    title: "Band-Aid Pack",
    price: 30,
    category: "Essentials",
    description: "Adhesive bandages for covering and protecting minor cuts and wounds. Convenient for on-the-go first aid.",
  ),
  Product(
    id: "6",
    title: "Toothpaste",
    price: 60,
    category: "Beauty",
    description: "Fluoride toothpaste for maintaining oral hygiene. Helps prevent cavities and promotes fresh breath.",
  ),
  Product(
    id: "7",
    title: "Sunscreen Lotion",
    price: 150,
    category: "Beauty",
    description: "Broad-spectrum sunscreen for sun protection. Guards against UVA and UVB rays, preventing sunburn.",
  ),
  Product(
    id: "8",
    title: "Contact Lens Solution",
    price: 120,
    category: "Medicine",
    description: "Sterile solution for cleaning and storing contact lenses. Keeps lenses comfortable and clear.",
  ),
  Product(
    id: "9",
    title: "Hand Sanitizer",
    price: 40,
    category: "Essentials",
    description: "Alcohol-based hand sanitizer for quick and effective hand hygiene. Convenient for on-the-go use.",
  ),
  Product(
    id: "10",
    title: "Digital Thermometer",
    price: 200,
    category: "Medical Devices",
    description: "Accurate digital thermometer for measuring body temperature. Suitable for oral, rectal, or underarm use.",
  ),
  Product(
    id: "11",
    title: "Lip Balm",
    price: 50,
    category: "Beauty",
    description: "Moisturizing lip balm for preventing dry and chapped lips. Provides long-lasting hydration.",
  ),
  Product(
    id: "12",
    title: "Antibacterial Soap",
    price: 35,
    category: "Essentials",
    description: "Soap with antibacterial properties for effective hand and body cleansing. Helps prevent the spread of germs.",
  ),
  Product(
    id: "13",
    title: "Eye Cream",
    price: 80,
    category: "Beauty",
    description: "Hydrating eye cream to reduce puffiness and dark circles. Nourishes the delicate skin around the eyes.",
  ),
  Product(
    id: "14",
    title: "Allergy Relief Tablets",
    price: 90,
    category: "Medicine",
    description: "Relieves allergy symptoms such as sneezing, runny nose, and itching. Non-drowsy formula.",
  ),
  Product(
    id: "15",
    title: "Shampoo",
    price: 70,
    category: "Beauty",
    description: "Gentle and nourishing shampoo for clean and healthy hair. Suitable for daily use.",
  ),
  Product(
    id: "16",
    title: "Pain Relief Cream",
    price: 60,
    category: "Medicine",
    description: "Topical cream for targeted pain relief. Soothes muscles and joints.",
  ),
  Product(
    id: "17",
    title: "Hand Cream",
    price: 45,
    category: "Beauty",
    description: "Moisturizing hand cream for soft and smooth hands. Absorbs quickly without a greasy feel.",
  ),
  Product(
    id: "18",
    title: "Multivitamin Capsules",
    price: 120,
    category: "Medicine",
    description: "Comprehensive multivitamin capsules for overall health support. Contains essential vitamins and minerals.",
  ),
  Product(
    id: "19",
    title: "Disinfectant Spray",
    price: 55,
    category: "Essentials",
    description: "Disinfectant spray for sanitizing surfaces and objects. Kills common household germs.",
  ),
  Product(
    id: "20",
    title: "Acne Treatment Gel",
    price: 75,
    category: "Beauty",
    description: "Topical gel for targeted acne treatment. Helps reduce inflammation and prevent breakouts.",
  ),
  Product(
    id: "21",
    title: "Antacid Tablets",
    price: 40,
    category: "Medicine",
    description: "Provides fast relief from heartburn and indigestion. Neutralizes excess stomach acid.",
  ),
  Product(
    id: "22",
    title: "Deodorant",
    price: 30,
    category: "Beauty",
    description: "Long-lasting and refreshing deodorant to keep you feeling confident throughout the day.",
  ),
  Product(
    id: "23",
    title: "First Aid Kit",
    price: 150,
    category: "Essentials",
    description: "Comprehensive first aid kit containing essential medical supplies for emergencies.",
  ),
  Product(
    id: "24",
    title: "Facial Cleanser",
    price: 55,
    category: "Beauty",
    description: "Gentle facial cleanser to remove dirt, oil, and makeup while nourishing the skin.",
  ),
  Product(
    id: "25",
    title: "Cough Syrup",
    price: 65,
    category: "Medicine",
    description: "Relieves cough and soothes sore throat. Non-drowsy formula for day and night use.",
  ),
  Product(
    id: "26",
    title: "Hair Conditioner",
    price: 80,
    category: "Beauty",
    description: "Hydrating and nourishing hair conditioner for smooth and manageable hair.",
  ),
  Product(
    id: "27",
    title: "Mosquito Repellent",
    price: 45,
    category: "Essentials",
    description: "Effective mosquito repellent lotion to protect against mosquito bites.",
  ),
  Product(
    id: "28",
    title: "Foundation",
    price: 100,
    category: "Beauty",
    description: "Buildable foundation for a flawless complexion. Long-wearing and natural finish.",
  ),
  Product(
    id: "29",
    title: "Nasal Spray",
    price: 70,
    category: "Medicine",
    description: "Relieves nasal congestion and sinus pressure. Fast-acting and non-drowsy.",
  ),
  Product(
    id: "30",
    title: "Wet Wipes",
    price: 25,
    category: "Essentials",
    description: "Convenient wet wipes for quick and easy cleaning on the go. Refreshing and gentle.",
  ),
  Product(
    id: "31",
    title: "Razor Kit",
    price: 50,
    category: "Beauty",
    description: "Complete razor kit for a smooth and comfortable shave. Includes razor and blades.",
  ),
  Product(
    id: "32",
    title: "Insulin Syringes",
    price: 90,
    category: "Medicine",
    description: "Sterile insulin syringes for precise and safe insulin injections.",
  ),
  Product(
    id: "33",
    title: "BB Cream",
    price: 70,
    category: "Beauty",
    description: "Multifunctional BB cream for natural-looking coverage, hydration, and sun protection.",
  ),
  Product(
    id: "34",
    title: "Toothbrush",
    price: 15,
    category: "Essentials",
    description: "Soft-bristle toothbrush for effective and gentle dental care. Comfortable grip for easy use.",
  ),
  Product(
    id: "35",
    title: "Antifungal Cream",
    price: 55,
    category: "Medicine",
    description: "Topical antifungal cream for the treatment of fungal infections on the skin.",
  ),
  Product(
    id: "36",
    title: "Body Lotion",
    price: 40,
    category: "Beauty",
    description: "Hydrating body lotion with a light and non-greasy formula. Leaves skin soft and smooth.",
  ),
  Product(
    id: "37",
    title: "Antiseptic Liquid",
    price: 35,
    category: "Essentials",
    description: "Multipurpose antiseptic liquid for wound cleaning and skin disinfection.",
  ),
  Product(
    id: "38",
    title: "Eye Drops",
    price: 50,
    category: "Medicine",
    description: "Soothing eye drops to relieve dryness, redness, and irritation.",
  ),
  Product(
    id: "39",
    title: "Lip Gloss",
    price: 25,
    category: "Beauty",
    description: "Shiny and hydrating lip gloss for a luscious and glossy finish.",
  ),
  Product(
    id: "40",
    title: "Insect Repellent Cream",
    price: 30,
    category: "Essentials",
    description: "Creamy insect repellent for protection against mosquitoes and other insects.",
  ),
  Product(
    id: "41",
    title: "Moisturizing Cream",
    price: 45,
    category: "Beauty",
    description: "Rich and moisturizing cream for intense hydration and soft, supple skin.",
  ),
  Product(
    id: "42",
    title: "Compression Bandages",
    price: 20,
    category: "Medicine",
    description: "Elastic compression bandages for providing support and reducing swelling.",
  ),
  Product(
      id: "43",
      title: "Nail Polish",
      price: 15,
      category: "Beauty",
      description: "Add a pop of color to your nails with our vibrant Nail Polish. This long-lasting formula provides high-gloss shine and is available in a variety of trendy shades to suit any occasion. Easy to apply and quick-drying, our Nail Polish is the perfect accessory to complete your manicure and express your unique style."
  ),
  Product(
    id: "44",
    title: "Digital Blood Pressure Monitor",
    price: 250,
    category: "Medical Devices",
    description: "Easy-to-use digital blood pressure monitor for accurate at-home blood pressure measurements. Features a digital display and memory function.",
  ),
  Product(
    id: "45",
    title: "Hair Gel",
    price: 35,
    category: "Beauty",
    description: "Strong-hold hair gel for styling and shaping hair. Provides long-lasting hold and a sleek finish.",
  ),
  Product(
    id: "46",
    title: "Diaper Rash Cream",
    price: 20,
    category: "Essentials",
    description: "Gentle and soothing diaper rash cream for the prevention and relief of diaper rash. Formulated with skin-nourishing ingredients.",
  ),
  Product(
    id: "47",
    title: "Prenatal Vitamins",
    price: 80,
    category: "Medicine",
    description: "Nutrient-rich prenatal vitamins to support the health of expectant mothers and fetal development. Contains essential vitamins and minerals.",
  ),
  Product(
    id: "48",
    title: "Tinted Moisturizer",
    price: 60,
    category: "Beauty",
    description: "Lightweight tinted moisturizer for a natural and even complexion. Provides hydration and a touch of color for a radiant look.",
  ),
  Product(
    id: "49",
    title: "Hand Soap",
    price: 25,
    category: "Essentials",
    description: "Gentle and moisturizing hand soap for effective hand hygiene. Leaves hands feeling clean and refreshed.",
  ),
  Product(
    id: "50",
    title: "Motion Sickness Tablets",
    price: 30,
    category: "Medicine",
    description: "Fast-acting motion sickness tablets to alleviate nausea and dizziness during travel. Suitable for adults and children.",
  ),
  Product(
    id: "51",
    title: "Hair Serum",
    price: 50,
    category: "Beauty",
    description: "Nourishing hair serum for added shine and smoothness. Tames frizz and protects hair from heat damage.",
  ),

];
